version: "3.9"
services:
  migration:
    container_name: flandria_db_migration
    image: florensiacommunity/flandria-backend
    command: flask db upgrade head
    environment:
      - APP_ENV=${APP_ENV:-prod}
    volumes:
      - type: bind
        source: ./database.db
        target: /home/flandria_user/flandria/database.db
        read_only: false
  frontend:
    container_name: flandria_frontend
    image: florensiacommunity/flandria-frontend
    expose:
      - "80"
    environment:
      - APP_ENV=${APP_ENV:-prod}
      - VIRTUAL_HOST=${SITE_NAME:-localhost}
      - VIRTUAL_PATH=/
      - LETSENCRYPT_HOST=${SITE_NAME:-localhost}
      - LETSENCRYPT_TEST=true  # TODO: Remove line after successful tests
    depends_on:
      - backend
    restart: always
  backend:
    container_name: flandria_backend
    image: florensiacommunity/flandria-backend
    expose:
      - "5000"
    environment:
      - APP_ENV=${APP_ENV:-prod}
      - VIRTUAL_HOST=${SITE_NAME:-localhost}
      - VIRTUAL_PATH=~^/(api|swaggerui)
      - VIRTUAL_PORT=5000
      - LETSENCRYPT_HOST=${SITE_NAME:-localhost}
      - LETSENCRYPT_TEST=true  # TODO: Remove line after successful tests
    volumes:
      - type: bind
        source: ./database.db
        target: /home/flandria_user/flandria/database.db
        read_only: false
    depends_on:
      - migration
      - nginx
    restart: always
  nginx:
    container_name: flandria_nginx
    image: nginxproxy/nginx-proxy
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - ssl_certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "80:80"
      - "443:443"
    restart: always
  cert-verificator:
    container_name: flandria_cert_validator
    image: nginxproxy/acme-companion
    environment:
      - NGINX_PROXY_CONTAINER=flandria_nginx
      - DEFAULT_EMAIL=${CERT_MAIL:-}
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - ssl_certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  conf:
  vhost:
  html:
  ssl_certs:
  acme:
