version: "3.9"
services:
  migration:
    container_name: flandria_db_migration
    image: florensiacommunity/flandria-backend
    command: flask db upgrade head
    environment:
      - APP_ENV=${APP_ENV:-prod}
    volumes:
      - type: bind
        source: ../database.db
        target: /home/flandria_user/flandria/database.db
        read_only: false
  backend:
    container_name: flandria_backend
    image: florensiacommunity/flandria-backend
    expose:
      - "5000"
    environment:
      - APP_ENV=${APP_ENV:-prod}
      - VIRTUAL_HOST=${SITE_NAME:-localhost}
    volumes:
      - type: bind
        source: ../database.db
        target: /home/flandria_user/flandria/database.db
        read_only: false
    depends_on:
      - migration
      - nginx
    restart: always
  nginx:
    container_name: flandria_nginx
    image: nginxproxy/nginx-proxy
    volumes:
      - type: bind
        source: ./ssl_certs
        target: /etc/nginx/certs
        read_only: true
      - type: bind
        source: /var/run/docker.sock
        target: /tmp/docker.sock
        read_only: true
    ports:
      - "80:80"
      - "443:443"
    restart: always
